import type { ModuleSymbols } from "../../analyzers/types.js";
import { D2Writer } from "./writer.js";
import { toD2Id, sortById, sortRelationships } from "./stability.js";

/**
 * Generate L4 Code diagram for a single module.
 * Shows: classes, interfaces, functions, structs and their relationships.
 */
export function generateCodeDiagram(
  symbols: ModuleSymbols,
  moduleName: string,
): string {
  const w = new D2Writer();

  w.comment(`C4 Code Diagram (Level 4) — ${moduleName}`);
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  const sorted = sortById(symbols.symbols);

  for (const sym of sorted) {
    const id = toD2Id(sym.id);
    const visPrefix =
      sym.visibility === "private" ? "- " : sym.visibility === "public" ? "+ " : "";
    w.shape(id, `${visPrefix}${sym.name}\\n\\n<<${sym.kind}>>`, {
      class: "code",
    });
  }

  if (sorted.length > 0) w.blank();

  const symIds = new Set(symbols.symbols.map((s) => s.id));
  const validRels = symbols.relationships.filter(
    (r) => symIds.has(r.sourceId) && symIds.has(r.targetId),
  );

  for (const rel of sortRelationships(validRels)) {
    const label = rel.label ? `${rel.kind}: ${rel.label}` : rel.kind;
    w.connection(toD2Id(rel.sourceId), toD2Id(rel.targetId), label);
  }

  return w.toString();
}
