import { D2Writer } from "./writer.js";
import { toD2Id, sortById, sortRelationships } from "./stability.js";
import type {
  ArchitectureModel,
  Component,
  CodeElement,
  CodeRelationship,
} from "../../analyzers/types.js";

export interface LanguageRenderingProfile {
  renderHeader(w: D2Writer, component: Component): void;
  renderElements(w: D2Writer, elements: CodeElement[]): void;
  renderExternalRefs(
    w: D2Writer,
    externalRels: CodeRelationship[],
    elements: CodeElement[],
  ): void;
  renderRelationships(w: D2Writer, relationships: CodeRelationship[]): void;
}

export function generateCodeDiagram(
  model: ArchitectureModel,
  component: Component,
  profile: LanguageRenderingProfile,
): string {
  const w = new D2Writer();
  const elements = sortById(
    (model.codeElements ?? []).filter((e) => e.componentId === component.id),
  );
  const elementIds = new Set(elements.map((e) => e.id));
  const rels = sortRelationships(model.codeRelationships ?? []);
  const internal: CodeRelationship[] = [];
  const external: CodeRelationship[] = [];
  for (const r of rels) {
    if (!elementIds.has(r.sourceId)) continue;
    if (elementIds.has(r.targetId)) internal.push(r);
    else external.push(r);
  }

  w.comment(`C4 Code-level diagram for component '${component.name}'`);
  w.comment("Generated by diagram-docs — do not edit");
  w.blank();
  profile.renderHeader(w, component);
  profile.renderElements(w, elements);
  profile.renderExternalRefs(w, external, elements);
  profile.renderRelationships(w, [...internal, ...external]);
  return w.toString();
}

// Re-export toD2Id for profiles to use for D2-safe identifiers.
export { toD2Id };
