import { D2Writer } from "./writer.js";
import { sortById, toD2Id } from "./stability.js";
import type { ArchitectureModel, Component } from "../../analyzers/types.js";
import type { DiagramSpec, EdgeSpec, VertexSpec } from "../projection/types.js";
import { projectCode } from "../projection/code.js";
import { flushProjectionWarnings } from "../projection/index.js";

/**
 * Per-language rendering profile. The emitter handles structural concerns
 * (boundary header, cross-component stubs); the profile only decides how
 * local elements and relationships are *drawn*.
 */
export interface LanguageRenderingProfile {
  renderHeader(w: D2Writer, component: { id: string; name: string }): void;
  renderElements(w: D2Writer, elements: VertexSpec[]): void;
  renderRelationships(w: D2Writer, relationships: EdgeSpec[]): void;
}

/**
 * Render a code-level DiagramSpec to D2.
 *
 * Structural decisions live here, not in profiles:
 * - The local component boundary is the `kind: "component"` vertex without
 *   the `cross-component` tag.
 * - Local elements are `kind: "code-element"` vertices parented to the local
 *   boundary; profiles render them.
 * - Cross-component elements are rendered uniformly as stroke-dashed boxes
 *   (language-agnostic — both supported profiles agreed on this shape, so it
 *   moved out of the profile API).
 */
export function emitCodeD2(
  spec: DiagramSpec,
  profile: LanguageRenderingProfile,
): string {
  const boundary = spec.vertices.find(
    (v) => v.kind === "component" && !v.tags?.includes("cross-component"),
  );
  if (!boundary) {
    throw new Error("projectCode must emit a local component boundary vertex");
  }

  const locals = sortById(
    spec.vertices.filter(
      (v) => v.kind === "code-element" && v.parentId === boundary.id,
    ),
  );
  const externals = sortById(
    spec.vertices.filter(
      (v) => v.kind === "code-element" && v.parentId !== boundary.id,
    ),
  );

  const w = new D2Writer();
  w.comment(`C4 Code-level diagram for component '${boundary.name}'`);
  w.comment("Generated by diagram-docs — do not edit");
  w.blank();
  profile.renderHeader(w, boundary);
  profile.renderElements(w, locals);
  renderExternalRefs(w, externals);
  profile.renderRelationships(w, spec.edges);
  return w.toString();
}

function renderExternalRefs(w: D2Writer, externals: VertexSpec[]): void {
  for (const v of externals) {
    w.shape(toD2Id(v.id), v.name, { "style.stroke-dash": "3" });
  }
}

/**
 * Public wrapper preserved for cli/commands/generate.ts. Accepts the model +
 * component pair, projects to a DiagramSpec, flushes warnings, then emits.
 */
export function generateCodeDiagram(
  model: ArchitectureModel,
  component: Component,
  profile: LanguageRenderingProfile,
): string {
  const spec = projectCode(model, component.id);
  flushProjectionWarnings(spec.warnings);
  return emitCodeD2(spec, profile);
}
