import type { ArchitectureModel } from "../../analyzers/types.js";
import type { DiagramSpec } from "../projection/types.js";
import { projectComponent } from "../projection/component.js";
import { D2Writer, wrapText } from "./writer.js";
import { toD2Id } from "./stability.js";

export interface ComponentDiagramOptions {
  /** Component IDs that have a C4 code-level diagram to link to. */
  codeLinks?: Set<string>;
  /** Rendered output extension (e.g. "svg", "png"). Defaults to "svg". */
  format?: string;
}

export function emitComponentD2(
  spec: DiagramSpec,
  options?: ComponentDiagramOptions,
): string {
  const w = new D2Writer();
  const boundary = spec.vertices.find(
    (v) => v.kind === "container" && !v.parentId,
  );
  if (!boundary) {
    throw new Error("projectComponent must emit a boundary container vertex");
  }
  const cId = toD2Id(boundary.id);
  w.comment(`C4 Component Diagram (Level 3) — ${boundary.name}`);
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  const components = spec.vertices.filter(
    (v) => v.kind === "component" && v.parentId === boundary.id,
  );
  const componentIds = new Set(components.map((c) => c.id));

  w.container(
    cId,
    `${boundary.name}\\n[Container: ${boundary.technology ?? ""}]`,
    () => {
      w.raw("class: system-boundary");
      w.blank();
      const ext = options?.format ?? "svg";
      for (const c of components) {
        const props: Record<string, string> = { class: "component" };
        if (options?.codeLinks?.has(c.id)) {
          props.link = `./components/${c.id}/c4-code.${ext}`;
        }
        w.shape(
          toD2Id(c.id),
          `${c.name}\\n\\n[Component: ${c.technology ?? ""}]\\n${wrapText(c.description ?? "")}`,
          props,
        );
      }
    },
  );
  w.blank();

  const externals = spec.vertices.filter(
    (v) => !v.parentId && v.id !== boundary.id,
  );
  for (const v of externals) {
    if (v.kind === "actor") {
      w.shape(
        toD2Id(v.id),
        `${v.name}\\n\\n[Person]\\n${wrapText(v.description ?? "")}`,
        { class: "person" },
      );
    } else if (v.kind === "external-system") {
      w.shape(toD2Id(v.id), `${v.name}\\n[External System]`, {
        class: "external-system",
      });
    } else if (v.kind === "container") {
      w.shape(toD2Id(v.id), `${v.name}\\n[Container: ${v.technology ?? ""}]`, {
        class: "container",
      });
    } else if (v.kind === "component") {
      w.shape(
        toD2Id(v.id),
        `${v.name}\\n\\n[Component: ${v.technology ?? ""}]`,
        { class: "component" },
      );
    }
  }
  if (externals.length > 0) w.blank();

  for (const e of spec.edges) {
    const src = componentIds.has(e.sourceId)
      ? `${cId}.${toD2Id(e.sourceId)}`
      : toD2Id(e.sourceId);
    const tgt = componentIds.has(e.targetId)
      ? `${cId}.${toD2Id(e.targetId)}`
      : toD2Id(e.targetId);
    const tech = e.technology ? ` [${e.technology}]` : "";
    w.connection(src, tgt, wrapText(`${e.label}${tech}`, 40, 1), {
      "style.font-size": "13",
    });
  }

  return w.toString();
}

export function generateComponentDiagram(
  model: ArchitectureModel,
  containerId: string,
  options?: ComponentDiagramOptions,
): string {
  return emitComponentD2(projectComponent(model, containerId), options);
}
