import type { ArchitectureModel } from "../../analyzers/types.js";
import { D2Writer, wrapText } from "./writer.js";
import { toD2Id, sortById, sortRelationships } from "./stability.js";

/**
 * Generate L3 Component diagram for a single container.
 * Shows: components within the container, relationships.
 */
export function generateComponentDiagram(
  model: ArchitectureModel,
  containerId: string,
): string {
  const container = model.containers.find((c) => c.id === containerId);
  if (!container) {
    throw new Error(`Container not found: ${containerId}`);
  }

  const components = model.components.filter(
    (c) => c.containerId === containerId,
  );
  const componentIds = new Set(components.map((c) => c.id));

  const w = new D2Writer();

  w.comment(`C4 Component Diagram (Level 3) — ${container.name}`);
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  // Container boundary with components inside
  const cId = toD2Id(containerId);
  w.container(cId, `${container.name}\\n[Container: ${container.technology}]`, () => {
    w.raw("class: system-boundary");
    w.blank();

    for (const comp of sortById(components)) {
      const id = toD2Id(comp.id);
      w.shape(
        id,
        `${comp.name}\\n\\n[Component: ${comp.technology}]\\n${wrapText(comp.description)}`,
        { "class": "component" },
      );
    }
  });

  w.blank();

  // External references (other containers, external systems)
  const referencedIds = new Set<string>();
  const componentRels = model.relationships.filter((r) => {
    const sourceInContainer = componentIds.has(r.sourceId);
    const targetInContainer = componentIds.has(r.targetId);
    if (sourceInContainer || targetInContainer) {
      if (!sourceInContainer) referencedIds.add(r.sourceId);
      if (!targetInContainer) referencedIds.add(r.targetId);
      return true;
    }
    return false;
  });

  // Add external shapes
  for (const refId of [...referencedIds].sort()) {
    const ext = model.externalSystems.find((e) => e.id === refId);
    const otherContainer = model.containers.find((c) => c.id === refId);

    if (ext) {
      w.shape(toD2Id(refId), `${ext.name}\\n[External System]`, {
        "class": "external-system",
      });
    } else if (otherContainer) {
      w.shape(
        toD2Id(refId),
        `${otherContainer.name}\\n[Container: ${otherContainer.technology}]`,
        { "class": "container" },
      );
    } else {
      w.shape(toD2Id(refId), refId);
    }
  }

  if (referencedIds.size > 0) w.blank();

  // Relationships
  for (const rel of sortRelationships(componentRels)) {
    const sourceId = componentIds.has(rel.sourceId)
      ? `${cId}.${toD2Id(rel.sourceId)}`
      : toD2Id(rel.sourceId);
    const targetId = componentIds.has(rel.targetId)
      ? `${cId}.${toD2Id(rel.targetId)}`
      : toD2Id(rel.targetId);

    const tech = rel.technology ? ` [${rel.technology}]` : "";
    w.connection(sourceId, targetId, `${rel.label}${tech}`);
  }

  return w.toString();
}
