import type { ArchitectureModel } from "../../analyzers/types.js";
import { D2Writer } from "./writer.js";
import { toD2Id, sortById, sortRelationships } from "./stability.js";

/**
 * Generate L1 Context diagram.
 * Shows: actors, the system, external systems, and relationships between them.
 */
export function generateContextDiagram(model: ArchitectureModel): string {
  const w = new D2Writer();

  w.comment("C4 Context Diagram (Level 1)");
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  // Actors
  for (const actor of sortById(model.actors)) {
    const id = toD2Id(actor.id);
    w.shape(id, `${actor.name}\\n\\n[Person]\\n${actor.description}`, {
      "class": "person",
    });
  }

  if (model.actors.length > 0) w.blank();

  // System boundary
  const sysId = toD2Id("system");
  w.shape(sysId, `${model.system.name}\\n\\n[Software System]\\n${model.system.description}`, {
    "class": "system",
  });

  w.blank();

  // External systems
  for (const ext of sortById(model.externalSystems)) {
    const id = toD2Id(ext.id);
    const tech = ext.technology ? `\\n[${ext.technology}]` : "";
    w.shape(id, `${ext.name}\\n\\n[External System]${tech}\\n${ext.description}`, {
      "class": "external-system",
    });
  }

  if (model.externalSystems.length > 0) w.blank();

  // Relationships (only context-level: between actors, system, and external systems)
  const contextIds = new Set([
    ...model.actors.map((a) => a.id),
    "system",
    ...model.externalSystems.map((e) => e.id),
    // Also include container IDs mapped to "system"
    ...model.containers.map((c) => c.id),
  ]);

  const contextRels = model.relationships.filter((r) => {
    const sourceIsContext =
      contextIds.has(r.sourceId) || model.containers.some((c) => c.id === r.sourceId);
    const targetIsContext =
      contextIds.has(r.targetId) || model.containers.some((c) => c.id === r.targetId);
    return sourceIsContext && targetIsContext;
  });

  for (const rel of sortRelationships(contextRels)) {
    // Map container refs to system
    const sourceId = model.containers.some((c) => c.id === rel.sourceId)
      ? sysId
      : toD2Id(rel.sourceId);
    const targetId = model.containers.some((c) => c.id === rel.targetId)
      ? sysId
      : toD2Id(rel.targetId);

    if (sourceId === targetId) continue; // Skip self-refs at context level

    const tech = rel.technology ? ` [${rel.technology}]` : "";
    w.connection(sourceId, targetId, `${rel.label}${tech}`);
  }

  return w.toString();
}
