import type { ArchitectureModel } from "../../analyzers/types.js";
import type { DiagramSpec } from "../projection/types.js";
import { projectContext } from "../projection/context.js";
import { flushProjectionWarnings } from "../projection/index.js";
import { D2Writer, wrapText } from "./writer.js";
import { toD2Id } from "./stability.js";

/**
 * Emit a D2 L1 Context diagram from a structural DiagramSpec.
 * No model traversal happens here — projection has already done it.
 */
export function emitContextD2(spec: DiagramSpec): string {
  const w = new D2Writer();
  w.comment("C4 Context Diagram (Level 1)");
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  const actors = spec.vertices.filter((v) => v.kind === "actor");
  for (const v of actors) {
    w.shape(
      toD2Id(v.id),
      `${v.name}\\n\\n[Person]\\n${wrapText(v.description ?? "")}`,
      { class: "person" },
    );
  }
  if (actors.length > 0) w.blank();

  const system = spec.vertices.find((v) => v.kind === "system");
  if (system) {
    w.shape(
      toD2Id(system.id),
      `${system.name}\\n\\n[Software System]\\n${wrapText(system.description ?? "")}`,
      { class: "system" },
    );
    w.blank();
  }

  const externals = spec.vertices.filter((v) => v.kind === "external-system");
  for (const v of externals) {
    const tech = v.technology ? `\\n[${v.technology}]` : "";
    w.shape(
      toD2Id(v.id),
      `${v.name}\\n\\n[External System]${tech}\\n${wrapText(v.description ?? "")}`,
      { class: "external-system" },
    );
  }
  if (externals.length > 0) w.blank();

  for (const e of spec.edges) {
    const tech = e.technology ? ` [${e.technology}]` : "";
    w.connection(
      toD2Id(e.sourceId),
      toD2Id(e.targetId),
      wrapText(`${e.label}${tech}`, 40, 1),
      { "style.font-size": "13" },
    );
  }

  return w.toString();
}

/** Public wrapper that owns the model→spec→D2 pipeline for L1. */
export function generateContextDiagram(model: ArchitectureModel): string {
  const spec = projectContext(model);
  flushProjectionWarnings(spec.warnings);
  return emitContextD2(spec);
}
