import type { ArchitectureModel } from "../../analyzers/types.js";
import type { DiagramSpec } from "../projection/types.js";
import { projectContainer } from "../projection/container.js";
import { D2Writer, wrapText } from "./writer.js";
import { toD2Id } from "./stability.js";

export interface ContainerDiagramOptions {
  componentLinks?: boolean;
  format?: string;
  /** Resolve a container ID to a relative link path for submodule mode. */
  submoduleLinkResolver?: (containerId: string) => string | null;
}

export function emitContainerD2(
  spec: DiagramSpec,
  options?: ContainerDiagramOptions,
): string {
  const w = new D2Writer();
  w.comment("C4 Container Diagram (Level 2)");
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  const actors = spec.vertices.filter((v) => v.kind === "actor");
  for (const v of actors) {
    w.shape(
      toD2Id(v.id),
      `${v.name}\\n\\n[Person]\\n${wrapText(v.description ?? "")}`,
      { class: "person" },
    );
  }
  if (actors.length > 0) w.blank();

  const system = spec.vertices.find((v) => v.kind === "system");
  if (!system) {
    throw new Error("projectContainer must emit a 'system' vertex");
  }
  const sysId = toD2Id(system.id);
  const containers = spec.vertices.filter(
    (v) => v.kind === "container" && v.parentId === system.id,
  );

  w.container(sysId, `${system.name}\\n[Software System]`, () => {
    w.raw("class: system-boundary");
    w.blank();
    for (const c of containers) {
      const props: Record<string, string> = { class: "container" };
      if (options?.submoduleLinkResolver) {
        const link = options.submoduleLinkResolver(c.id);
        if (link) props.link = link;
      } else if (options?.componentLinks) {
        const ext = options.format ?? "svg";
        props.link = `./containers/${c.id}/c3-component.${ext}`;
      }
      const tech = c.technology ?? "";
      w.shape(
        toD2Id(c.id),
        `${c.name}\\n\\n[Container: ${tech}]\\n${wrapText(c.description ?? "")}`,
        props,
      );
    }
  });
  w.blank();

  const externals = spec.vertices.filter((v) => v.kind === "external-system");
  for (const v of externals) {
    const tech = v.technology ? `\\n[${v.technology}]` : "";
    const isLibrary = v.tags?.includes("library") ?? false;
    const label = isLibrary
      ? `${v.name}\\n\\n[Library]${tech}\\n${wrapText(v.description ?? "")}`
      : `${v.name}\\n\\n[External System]${tech}\\n${wrapText(v.description ?? "")}`;
    w.shape(toD2Id(v.id), label, {
      class: isLibrary ? "library" : "external-system",
    });
  }
  if (externals.length > 0) w.blank();

  for (const e of spec.edges) {
    const containerIds = new Set(containers.map((c) => c.id));
    const src = containerIds.has(e.sourceId)
      ? `${sysId}.${toD2Id(e.sourceId)}`
      : toD2Id(e.sourceId);
    const tgt = containerIds.has(e.targetId)
      ? `${sysId}.${toD2Id(e.targetId)}`
      : toD2Id(e.targetId);
    const tech = e.technology ? ` [${e.technology}]` : "";
    w.connection(src, tgt, wrapText(`${e.label}${tech}`, 40, 1), {
      "style.font-size": "13",
    });
  }

  return w.toString();
}

export function generateContainerDiagram(
  model: ArchitectureModel,
  options?: ContainerDiagramOptions,
): string {
  return emitContainerD2(projectContainer(model), options);
}
