import type { ArchitectureModel } from "../../analyzers/types.js";
import { D2Writer, wrapText } from "./writer.js";
import { toD2Id, sortById, sortRelationships } from "./stability.js";

export interface ContainerDiagramOptions {
  componentLinks?: boolean;
  format?: string;
  /** Resolve a container ID to a relative link path for submodule mode. */
  submoduleLinkResolver?: (containerId: string) => string | null;
}

/**
 * Generate L2 Container diagram.
 * Shows: actors, containers within the system boundary, external systems.
 */
export function generateContainerDiagram(
  model: ArchitectureModel,
  options?: ContainerDiagramOptions,
): string {
  // --- Pre-compute relationships so we know which containers are connected ---
  const sysId = toD2Id("system");
  const containerIds = new Set(model.containers.map((c) => c.id));
  const componentToContainer = new Map<string, string>();
  for (const comp of model.components ?? []) {
    componentToContainer.set(comp.id, comp.containerId);
  }

  const allIds = new Set([
    ...model.actors.map((a) => a.id),
    ...model.containers.map((c) => c.id),
    ...model.externalSystems.map((e) => e.id),
    ...(model.components ?? []).map((c) => c.id),
  ]);

  // Resolve a relationship endpoint: component → parent container, then qualify
  const resolveId = (id: string): string => {
    const mapped = componentToContainer.get(id) ?? id;
    return containerIds.has(mapped)
      ? `${sysId}.${toD2Id(mapped)}`
      : toD2Id(mapped);
  };

  const candidateRels = model.relationships.filter(
    (r) => allIds.has(r.sourceId) && allIds.has(r.targetId),
  );

  // Build deduplicated edge list and collect connected container IDs
  const seenEdges = new Set<string>();
  const connectedContainerIds = new Set<string>();
  interface ResolvedRel {
    sourceId: string;
    targetId: string;
    label: string;
    technology?: string;
  }
  const resolvedRels: ResolvedRel[] = [];

  for (const rel of sortRelationships(candidateRels)) {
    const sourceId = resolveId(rel.sourceId);
    const targetId = resolveId(rel.targetId);

    if (sourceId === targetId) continue;

    const edgeKey = `${sourceId}->${targetId}`;
    if (seenEdges.has(edgeKey)) continue;
    seenEdges.add(edgeKey);

    resolvedRels.push({
      sourceId,
      targetId,
      label: rel.label,
      technology: rel.technology,
    });

    // Track which containers participate in at least one edge
    for (const container of model.containers) {
      const qualifiedId = `${sysId}.${toD2Id(container.id)}`;
      if (sourceId === qualifiedId || targetId === qualifiedId) {
        connectedContainerIds.add(container.id);
      }
    }
  }

  // --- Now emit the diagram, skipping dangling containers ---
  const w = new D2Writer();

  w.comment("C4 Container Diagram (Level 2)");
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  // Actors
  for (const actor of sortById(model.actors)) {
    const id = toD2Id(actor.id);
    w.shape(
      id,
      `${actor.name}\\n\\n[Person]\\n${wrapText(actor.description)}`,
      {
        class: "person",
      },
    );
  }

  if (model.actors.length > 0) w.blank();

  // System boundary with containers inside (only those with at least one relationship)
  w.container(sysId, `${model.system.name}\\n[Software System]`, () => {
    w.raw("class: system-boundary");
    w.blank();

    for (const container of sortById(model.containers)) {
      if (!connectedContainerIds.has(container.id)) continue;

      const id = toD2Id(container.id);
      const props: Record<string, string> = { class: "container" };

      // Link resolution: submodule resolver takes priority, then standard componentLinks
      if (options?.submoduleLinkResolver) {
        const link = options.submoduleLinkResolver(container.id);
        if (link) props.link = link;
      } else if (options?.componentLinks) {
        const ext = options.format ?? "svg";
        props.link = `./containers/${container.id}/c3-component.${ext}`;
      }

      w.shape(
        id,
        `${container.name}\\n\\n[Container: ${container.technology}]\\n${wrapText(container.description)}`,
        props,
      );
    }
  });

  w.blank();

  // External systems
  for (const ext of sortById(model.externalSystems)) {
    const id = toD2Id(ext.id);
    const tech = ext.technology ? `\\n[${ext.technology}]` : "";
    w.shape(
      id,
      `${ext.name}\\n\\n[External System]${tech}\\n${wrapText(ext.description)}`,
      {
        class: "external-system",
      },
    );
  }

  if (model.externalSystems.length > 0) w.blank();

  // Relationships
  for (const rel of resolvedRels) {
    const tech = rel.technology ? ` [${rel.technology}]` : "";
    w.connection(
      rel.sourceId,
      rel.targetId,
      wrapText(`${rel.label}${tech}`, 40, 1),
      { "style.font-size": "13" },
    );
  }

  return w.toString();
}
