import type { ArchitectureModel } from "../../analyzers/types.js";
import { D2Writer, wrapText } from "./writer.js";
import { toD2Id, sortById, sortRelationships } from "./stability.js";

export interface ContainerDiagramOptions {
  componentLinks?: boolean;
  format?: string;
  /** Resolve a container ID to a relative link path for submodule mode. */
  submoduleLinkResolver?: (containerId: string) => string | null;
}

/**
 * Generate L2 Container diagram.
 * Shows: actors, containers within the system boundary, external systems.
 */
export function generateContainerDiagram(
  model: ArchitectureModel,
  options?: ContainerDiagramOptions,
): string {
  const w = new D2Writer();

  w.comment("C4 Container Diagram (Level 2)");
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  // Actors
  for (const actor of sortById(model.actors)) {
    const id = toD2Id(actor.id);
    w.shape(id, `${actor.name}\\n\\n[Person]\\n${wrapText(actor.description)}`, {
      "class": "person",
    });
  }

  if (model.actors.length > 0) w.blank();

  // System boundary with containers inside
  const sysId = toD2Id("system");
  w.container(sysId, `${model.system.name}\\n[Software System]`, () => {
    w.raw("class: system-boundary");
    w.blank();

    for (const container of sortById(model.containers)) {
      const id = toD2Id(container.id);
      const props: Record<string, string> = { "class": "container" };

      // Link resolution: submodule resolver takes priority, then standard componentLinks
      if (options?.submoduleLinkResolver) {
        const link = options.submoduleLinkResolver(container.id);
        if (link) props.link = link;
      } else if (options?.componentLinks) {
        const ext = options.format ?? "svg";
        props.link = `./containers/${container.id}/c3-component.${ext}`;
      }

      w.shape(
        id,
        `${container.name}\\n\\n[Container: ${container.technology}]\\n${wrapText(container.description)}`,
        props,
      );
    }
  });

  w.blank();

  // External systems
  for (const ext of sortById(model.externalSystems)) {
    const id = toD2Id(ext.id);
    const tech = ext.technology ? `\\n[${ext.technology}]` : "";
    w.shape(id, `${ext.name}\\n\\n[External System]${tech}\\n${wrapText(ext.description)}`, {
      "class": "external-system",
    });
  }

  if (model.externalSystems.length > 0) w.blank();

  // Relationships
  const containerIds = new Set(model.containers.map((c) => c.id));
  const allIds = new Set([
    ...model.actors.map((a) => a.id),
    ...model.containers.map((c) => c.id),
    ...model.externalSystems.map((e) => e.id),
  ]);

  const containerRels = model.relationships.filter(
    (r) => allIds.has(r.sourceId) && allIds.has(r.targetId),
  );

  for (const rel of sortRelationships(containerRels)) {
    const sourceId = containerIds.has(rel.sourceId)
      ? `${sysId}.${toD2Id(rel.sourceId)}`
      : toD2Id(rel.sourceId);
    const targetId = containerIds.has(rel.targetId)
      ? `${sysId}.${toD2Id(rel.targetId)}`
      : toD2Id(rel.targetId);

    const tech = rel.technology ? ` [${rel.technology}]` : "";
    w.connection(sourceId, targetId, `${rel.label}${tech}`);
  }

  return w.toString();
}
