import type { ArchitectureModel } from "../../analyzers/types.js";
import { D2Writer, wrapText } from "./writer.js";
import { toD2Id, sortById, sortRelationships } from "./stability.js";

/**
 * Generate L1 Context diagram.
 * Shows: actors, the system, external systems, and relationships between them.
 */
export function generateContextDiagram(model: ArchitectureModel): string {
  const w = new D2Writer();

  w.comment("C4 Context Diagram (Level 1)");
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  // Actors
  for (const actor of sortById(model.actors)) {
    const id = toD2Id(actor.id);
    w.shape(
      id,
      `${actor.name}\\n\\n[Person]\\n${wrapText(actor.description)}`,
      {
        class: "person",
      },
    );
  }

  if (model.actors.length > 0) w.blank();

  // System boundary
  const sysId = toD2Id("system");
  w.shape(
    sysId,
    `${model.system.name}\\n\\n[Software System]\\n${wrapText(model.system.description)}`,
    {
      class: "system",
    },
  );

  w.blank();

  // External systems
  for (const ext of sortById(model.externalSystems)) {
    const id = toD2Id(ext.id);
    const tech = ext.technology ? `\\n[${ext.technology}]` : "";
    w.shape(
      id,
      `${ext.name}\\n\\n[External System]${tech}\\n${wrapText(ext.description)}`,
      {
        class: "external-system",
      },
    );
  }

  if (model.externalSystems.length > 0) w.blank();

  // Relationships (only context-level: between actors, system, and external systems)
  // Include actors, external systems, containers, and components — the latter two
  // are all mapped to "system" so that any relationship reaching an external system
  // (even from a deeply nested component) surfaces at the context level.
  const actorIds = new Set(model.actors.map((a) => a.id));
  const externalIds = new Set(model.externalSystems.map((e) => e.id));
  const containerIds = new Set(model.containers.map((c) => c.id));
  const componentIds = new Set((model.components ?? []).map((c) => c.id));
  const internalIds = new Set([...containerIds, ...componentIds]);

  const contextIds = new Set([
    ...actorIds,
    "system",
    ...externalIds,
    ...containerIds,
    ...componentIds,
  ]);

  const contextRels = model.relationships.filter((r) => {
    return contextIds.has(r.sourceId) && contextIds.has(r.targetId);
  });

  // Deduplicate: multiple component→external relationships collapse into one system→external edge
  const seenEdges = new Set<string>();

  for (const rel of sortRelationships(contextRels)) {
    // Map container and component refs to system
    const sourceId = internalIds.has(rel.sourceId)
      ? sysId
      : toD2Id(rel.sourceId);
    const targetId = internalIds.has(rel.targetId)
      ? sysId
      : toD2Id(rel.targetId);

    if (sourceId === targetId) continue; // Skip self-refs at context level

    // Skip duplicate edges (component-level rels can collapse into the same system→external edge)
    const edgeKey = `${sourceId}->${targetId}`;
    if (seenEdges.has(edgeKey)) continue;
    seenEdges.add(edgeKey);

    const tech = rel.technology ? ` [${rel.technology}]` : "";
    w.connection(sourceId, targetId, wrapText(`${rel.label}${tech}`, 40, 1), {
      "style.font-size": "13",
    });
  }

  return w.toString();
}
