import { D2Writer } from "./writer.js";

/**
 * Generate C4-style definitions for D2 diagrams.
 * Uses D2 vars and classes for consistent C4 styling.
 */
export function generateStyles(theme: number, layout: string): string {
  const w = new D2Writer();

  w.comment("C4 Architecture Diagram Styles");
  w.comment("Auto-generated by diagram-docs — do not edit");
  w.blank();

  // Direction and layout
  w.raw("direction: right");
  w.blank();

  // Style classes for C4 elements
  w.raw("classes: {");
  w.raw("  person: {");
  w.raw("    shape: person");
  w.raw("    style.fill: \"#08427B\"");
  w.raw("    style.font-color: \"#ffffff\"");
  w.raw("    style.stroke: \"#073B6F\"");
  w.raw("  }");
  w.raw("  system: {");
  w.raw("    shape: rectangle");
  w.raw("    style.fill: \"#1168BD\"");
  w.raw("    style.font-color: \"#ffffff\"");
  w.raw("    style.stroke: \"#0E5CA8\"");
  w.raw("    style.border-radius: 8");
  w.raw("  }");
  w.raw("  external-system: {");
  w.raw("    shape: rectangle");
  w.raw("    style.fill: \"#999999\"");
  w.raw("    style.font-color: \"#ffffff\"");
  w.raw("    style.stroke: \"#8A8A8A\"");
  w.raw("    style.border-radius: 8");
  w.raw("  }");
  w.raw("  container: {");
  w.raw("    shape: rectangle");
  w.raw("    style.fill: \"#438DD5\"");
  w.raw("    style.font-color: \"#ffffff\"");
  w.raw("    style.stroke: \"#3C7FC0\"");
  w.raw("    style.border-radius: 8");
  w.raw("  }");
  w.raw("  component: {");
  w.raw("    shape: rectangle");
  w.raw("    style.fill: \"#85BBF0\"");
  w.raw("    style.font-color: \"#000000\"");
  w.raw("    style.stroke: \"#78A8D8\"");
  w.raw("    style.border-radius: 8");
  w.raw("  }");
  w.raw("  system-boundary: {");
  w.raw("    shape: rectangle");
  w.raw("    style.fill: \"#ffffff\"");
  w.raw("    style.stroke: \"#444444\"");
  w.raw("    style.stroke-dash: 5");
  w.raw("    style.border-radius: 8");
  w.raw("  }");
  w.raw("}");

  return w.toString();
}
