/**
 * C4-style class definitions for D2 diagrams.
 * Single static definition used by all diagram levels.
 */
export const STYLES_D2 = `\
# C4 Architecture Diagram Styles
# Auto-generated by diagram-docs — do not edit

direction: right

classes: {
  person: {
    shape: person
    width: 180
    height: 230
    style.fill: "#08427B"
    style.font-color: "#ffffff"
    style.stroke: "#073B6F"
  }
  system: {
    shape: rectangle
    style.fill: "#1168BD"
    style.font-color: "#ffffff"
    style.stroke: "#0E5CA8"
    style.border-radius: 8
  }
  external-system: {
    shape: rectangle
    style.fill: "#999999"
    style.font-color: "#ffffff"
    style.stroke: "#8A8A8A"
    style.border-radius: 8
  }
  container: {
    shape: rectangle
    style.fill: "#438DD5"
    style.font-color: "#ffffff"
    style.stroke: "#3C7FC0"
    style.border-radius: 8
  }
  component: {
    shape: rectangle
    style.fill: "#85BBF0"
    style.font-color: "#000000"
    style.stroke: "#78A8D8"
    style.border-radius: 8
  }
  system-boundary: {
    shape: rectangle
    style.fill: "#ffffff"
    style.stroke: "#444444"
    style.stroke-dash: 5
    style.border-radius: 8
  }
}
`;
