import { Command } from "commander";
import * as fs from "node:fs";
import * as path from "node:path";
import { stringify as stringifyYaml } from "yaml";
import { loadConfig } from "../../config/loader.js";
import { buildModel } from "../../core/model-builder.js";
import { readManifest, writeManifest, createDefaultManifest } from "../../core/manifest.js";
import {
  buildModelWithLLM,
  serializeModel,
  LLMUnavailableError,
  LLMCallError,
  LLMOutputError,
} from "../../core/llm-model-builder.js";
import { createFrame } from "../frame.js";
import type { RawStructure } from "../../analyzers/types.js";

export const modelCommand = new Command("model")
  .description(
    "Generate architecture-model.yaml from raw scan output",
  )
  .option(
    "-i, --input <path>",
    "Path to raw-structure.json",
    ".diagram-docs/raw-structure.json",
  )
  .option(
    "-o, --output <path>",
    "Output path",
    "architecture-model.yaml",
  )
  .option("-c, --config <path>", "Path to diagram-docs.yaml")
  .option("--llm", "Use LLM to generate model (requires Claude Code or Copilot CLI)")
  .action(async (options) => {
    const { config, configDir } = loadConfig(options.config);

    const inputPath = path.resolve(options.input);
    if (!fs.existsSync(inputPath)) {
      console.error(
        `Error: raw-structure.json not found at ${inputPath}\n` +
          "Run 'diagram-docs scan' first to produce it.",
      );
      process.exit(1);
    }

    const rawStructure: RawStructure = JSON.parse(
      fs.readFileSync(inputPath, "utf-8"),
    );

    let yamlContent: string;
    const scanChecksum = rawStructure.checksum;

    if (options.llm) {
      // Read config YAML for LLM context
      const configPath = path.resolve(configDir, "diagram-docs.yaml");
      const configYaml = fs.existsSync(configPath)
        ? fs.readFileSync(configPath, "utf-8")
        : undefined;

      // Read existing model for update mode
      const outputPath = path.resolve(options.output);
      const existingModelYaml = fs.existsSync(outputPath)
        ? fs.readFileSync(outputPath, "utf-8")
        : undefined;

      const isAnchorMode = !existingModelYaml?.trim();

      try {
        if (isAnchorMode) {
          // Anchor mode: parallel builder manages its own UI for all app counts
          const model = await buildModelWithLLM({
            rawStructure,
            config,
            configYaml,
            existingModelYaml,
          });
          yamlContent = serializeModel(model);

          fs.writeFileSync(outputPath, yamlContent, "utf-8");
          console.error(`Model written to ${path.relative(process.cwd(), outputPath)}`);
        } else {
          // Update mode: use Frame for the single iterative LLM call
          const frame = createFrame("LLM Agent");
          const model = await buildModelWithLLM({
            rawStructure,
            config,
            configYaml,
            existingModelYaml,
            onStatus(status) {
              frame.update([
                { text: status, spinner: true },
                { text: `Model: ${config.llm.model}` },
              ]);
            },
            onProgress({ line, final: done, kind }) {
              frame.log(line, done, kind);
            },
          });
          frame.stop([
            {
              text: `${model.containers.length} container(s), ` +
                `${model.components.length} component(s), ` +
                `${model.relationships.length} relationship(s)`,
            },
          ]);
          yamlContent = serializeModel(model);

          fs.writeFileSync(outputPath, yamlContent, "utf-8");
          console.error(`Model written to ${path.relative(process.cwd(), outputPath)}`);
        }
      } catch (err) {
        if (
          err instanceof LLMUnavailableError ||
          err instanceof LLMCallError ||
          err instanceof LLMOutputError
        ) {
          console.error(`Error: ${err.message}`);
          console.error("  Per-app agent logs may be available in .diagram-docs/logs/");
          process.exit(1);
        }
        throw err;
      }
    } else {
      const model = buildModel({ config, rawStructure });

      yamlContent =
        "# Architecture Model — generated by diagram-docs model\n" +
        "# Edit this file to refine names, descriptions, and relationships.\n" +
        "# Actors are intentionally left empty — add your own.\n" +
        "\n" +
        stringifyYaml(model, { lineWidth: 120 });

      const outputPath = path.resolve(options.output);
      fs.writeFileSync(outputPath, yamlContent, "utf-8");
      console.error(`Model written to ${path.relative(process.cwd(), outputPath)}`);
      console.error(
        `  ${model.containers.length} container(s), ` +
          `${model.components.length} component(s), ` +
          `${model.externalSystems.length} external system(s), ` +
          `${model.relationships.length} relationship(s)`,
      );
    }

    // Record scan checksum so generate can detect stale models
    if (scanChecksum) {
      const manifest = readManifest(configDir) ?? createDefaultManifest();
      manifest.lastModel = {
        timestamp: new Date().toISOString(),
        checksum: scanChecksum,
      };
      writeManifest(configDir, manifest);
    }
  });
