import { Command } from "commander";
import * as fs from "node:fs";
import * as path from "node:path";
import { stringify as stringifyYaml } from "yaml";
import { loadConfig } from "../../config/loader.js";
import { buildModel } from "../../core/model-builder.js";
import type { RawStructure } from "../../analyzers/types.js";

export const modelCommand = new Command("model")
  .description(
    "Generate architecture-model.yaml from raw scan output (deterministic, no LLM)",
  )
  .option(
    "-i, --input <path>",
    "Path to raw-structure.json",
    ".diagram-docs/raw-structure.json",
  )
  .option(
    "-o, --output <path>",
    "Output path",
    "architecture-model.yaml",
  )
  .option("-c, --config <path>", "Path to diagram-docs.yaml")
  .action((options) => {
    const { config } = loadConfig(options.config);

    const inputPath = path.resolve(options.input);
    if (!fs.existsSync(inputPath)) {
      console.error(
        `Error: raw-structure.json not found at ${inputPath}\n` +
          "Run 'diagram-docs scan' first to produce it.",
      );
      process.exit(1);
    }

    const rawStructure: RawStructure = JSON.parse(
      fs.readFileSync(inputPath, "utf-8"),
    );

    const model = buildModel({ config, rawStructure });

    const yamlContent =
      "# Architecture Model — generated by diagram-docs model\n" +
      "# Edit this file to refine names, descriptions, and relationships.\n" +
      "# Actors are intentionally left empty — add your own.\n" +
      "\n" +
      stringifyYaml(model, { lineWidth: 120 });

    const outputPath = path.resolve(options.output);
    fs.writeFileSync(outputPath, yamlContent, "utf-8");
    console.error(`Model written to ${path.relative(process.cwd(), outputPath)}`);
    console.error(
      `  ${model.containers.length} container(s), ` +
        `${model.components.length} component(s), ` +
        `${model.externalSystems.length} external system(s), ` +
        `${model.relationships.length} relationship(s)`,
    );
  });
