#!/usr/bin/env sh
set -e

STAGED_FILES=$(git diff --name-only --cached)

npm run format
npm run lint -- --fix

if [ -n "$STAGED_FILES" ]; then
  while IFS= read -r f; do git add -- "$f"; done <<< "$STAGED_FILES"
fi
